# When running this in a new account.
# The account must be added to trust relationships in
# arn:aws:iam::535625058381:role/bluegrass-codecommit-cross-account-role

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Xylem HTTPS Service for CoAP <-> HTTP Proxy Stack

Parameters:
  AccountPrefix:
    Type: String
  ApplicationName:
    Type: String
  ArtifactBucketName:
    Type: String
  ConnectionArn:
    Type: String
  Environment:
    Type: String
  GitOrg:
    Type: String
  Stack:
    Type: String

Resources:
     
  # Main API Stack
  ApiPipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ApiRepositoryBranch: !Ref Environment
        ApiRepositoryName: !Ref ApplicationName
        ApplicationName: !Ref ApplicationName
        ArtifactBucketName: !Ref ArtifactBucketName
        CloudFormationDeploymentRoleArn:
          Fn::ImportValue: !Sub canvas-coap-proxy-${Environment}-CloudFormationDeploymentRoleArn
        CodeBuildProjectRoleArn:
          Fn::ImportValue: !Sub canvas-coap-proxy-${Environment}-CodeBuildProjectRoleArn
        ConnectionArn: !Ref ConnectionArn
        ContainerName: http-service-proxy
        Environment: !Ref Environment
        FullRepositoryId: !Sub ${GitOrg}/${ApplicationName}
        KMSKeyArn:
          Fn::ImportValue: !Sub canvas-coap-proxy-${Environment}-KMSKeyArn
        PipeLineRoleArn:
          Fn::ImportValue: !Sub canvas-coap-proxy-${Environment}-CodePipelineRoleArn
        ResourceGroup: !Sub ${Stack}-${Environment}
        Stack: !Ref Stack
        EcrRepositoryUri:
          Fn::GetAtt: [EcsServiceStack, Outputs.EcrRepositoryUri]

        ClusterName:
          Fn::ImportValue: !Sub canvas-coap-proxy-${Environment}-ClusterName


      Tags:
        - Key: ResourceGroup
          Value: !Sub ${Stack}-${Environment}
      TemplateURL: !Sub https://${ArtifactBucketName}.s3.amazonaws.com/cloudformation/cfnCodePipelineTemplate.yaml
      TimeoutInMinutes: 5

  EcsServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ApplicationName: !Ref ApplicationName
        ClusterArn:
          Fn::ImportValue: !Sub canvas-coap-proxy-${Environment}-ClusterArn
        ClusterVpcId:
          Fn::ImportValue: !Sub canvas-coap-proxy-${Environment}-VpcId
        ContainerName: http-service-proxy
        Environment: !Ref Environment
        Subnet:
          Fn::ImportValue: !Sub canvas-coap-proxy-${Environment}-PrivateSubnet1

      Tags:
        - Key: ResourceGroup
          Value: !Sub ${Stack}-${Environment}
      TemplateURL: !Sub https://${ArtifactBucketName}.s3.amazonaws.com/cloudformation/cfnEcsServiceTemplate.yaml
      TimeoutInMinutes: 5