# When running this in a new account.
# The account must be added to trust relationships in
# arn:aws:iam::535625058381:role/bluegrass-codecommit-cross-account-role

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Xylem HTTPS Service for CoAP <-> HTTP Proxy Stack

Parameters:
  AccountPrefix:
    Type: String
  ApplicationName:
    Type: String
  ArtifactBucketName:
    Type: String
  ConnectionArn:
    Type: String
  Environment:
    Type: String
  GitOrg:
    Type: String
  Stack:
    Type: String

Resources:
  SdkLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket: !Ref ArtifactBucketName
        S3Key: layers/aws-sdk-v3/nodejs.zip
      Description: AWS SDK V3Layer
      LayerName: !Sub xylem-http-proxy-${Environment}-AWS-SDK-V3-Layer
      
  # Main API Stack
  ApiPipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ApiRepositoryBranch: !Ref Environment
        ApiRepositoryName: !Ref ApplicationName
        ApplicationName: !Ref ApplicationName
        ArtifactBucketName: !Ref ArtifactBucketName
        CloudFormationDeploymentRoleArn:
          Fn::ImportValue: !Sub canvas-coap-proxy-${Environment}-CloudFormationDeploymentRoleArn
        CodeBuildProjectRoleArn:
          Fn::ImportValue: !Sub canvas-coap-proxy-${Environment}-CodeBuildProjectRoleArn
        ConnectionArn: !Ref ConnectionArn
        Environment: !Ref Environment
        FullRepositoryId: !Sub ${GitOrg}/${ApplicationName}
        KMSKeyArn:
          Fn::ImportValue: !Sub canvas-coap-proxy-${Environment}-KMSKeyArn
        OutpostBucketName: !Ref OutpostBucketName
        PipeLineRoleArn:
          Fn::ImportValue: !Sub canvas-coap-proxy-${Environment}-CodePipelineRoleArn
        ResourceGroup: !Sub ${Stack}-${Environment}
        SdkLayerArn:
          Fn::ImportValue: !Sub ${Stack}-common-${Environment}-SdkLambdaLayerArn
        Stack: !Ref Stack

      Tags:
        - Key: ResourceGroup
          Value: !Sub ${Stack}-${Environment}
      TemplateURL: !Sub https://${ArtifactBucketName}.s3.amazonaws.com/cloudformation/cfnCodePipelineTemplate.yaml
      TimeoutInMinutes: 5
